### PR TITLE
Check for leaks in orchestrator package tests

### PR DESCRIPTION
**Pull request by samrabelachew**
Checked for leaks in orchestrator package test using goleaks [library](https://github.com/uber-go/goleak). Added cancel() to one test to pass.

### CODE REVIEW

**Comment by samrabelachew** [comment]
@jyotimahapatra

**Review by jyotimahapatra — APPROVED** [review]

**Comment by jyotimahapatra** [comment]
@samrabelachew can you help us fix the flakey test that is preventing the PR to succeed.

**Comment by jyotimahapatra** [comment]
@samrabelachew can you merge master to get rid of flakey test in this PR?

**Comment by samrabelachew** [comment]
> @samrabelachew can you merge master to get rid of flakey test in this PR?

done

**Review by jyotimahapatra — APPROVED** [review]

**Pull request merged**
